ServerEvents.recipes((event) => {
  event.recipes.ars_nouveau.enchanting_apparatus(
    [
      'eternal_starlight:red_starlight_crystal_shard',
      '#eternal_starlight:blaze_crystal_ingredients',
      'eternal_starlight:red_starlight_crystal_shard',
      '#eternal_starlight:blaze_crystal_ingredients',
      'eternal_starlight:red_starlight_crystal_shard',
      '#eternal_starlight:blaze_crystal_ingredients',
      'eternal_starlight:red_starlight_crystal_shard',
      '#eternal_starlight:blaze_crystal_ingredients',
    ],
    'eternal_starlight:red_starlight_crystal_shard',
    'eternal_starlight:blaze_crystal',
    10000,
  );

  event.recipes.ars_nouveau.enchanting_apparatus(
    [
      'eternal_starlight:red_starlight_crystal_shard',
      '#eternal_starlight:wind_crystal_ingredients',
      'eternal_starlight:red_starlight_crystal_shard',
      '#eternal_starlight:wind_crystal_ingredients',
      'eternal_starlight:red_starlight_crystal_shard',
      '#eternal_starlight:wind_crystal_ingredients',
      'eternal_starlight:red_starlight_crystal_shard',
      '#eternal_starlight:wind_crystal_ingredients',
    ],
    'eternal_starlight:red_starlight_crystal_shard',
    'eternal_starlight:wind_crystal',
    10000,
  );

  event.recipes.ars_nouveau.enchanting_apparatus(
    [
      'eternal_starlight:red_starlight_crystal_shard',
      '#eternal_starlight:terra_crystal_ingredients',
      'eternal_starlight:red_starlight_crystal_shard',
      '#eternal_starlight:terra_crystal_ingredients',
      'eternal_starlight:red_starlight_crystal_shard',
      '#eternal_starlight:terra_crystal_ingredients',
      'eternal_starlight:red_starlight_crystal_shard',
      '#eternal_starlight:terra_crystal_ingredients',
    ],
    'eternal_starlight:red_starlight_crystal_shard',
    'eternal_starlight:terra_crystal',
    10000,
  );

  event.recipes.ars_nouveau.enchanting_apparatus(
    [
      'eternal_starlight:red_starlight_crystal_shard',
      '#eternal_starlight:lunar_crystal_ingredients',
      'eternal_starlight:red_starlight_crystal_shard',
      '#eternal_starlight:lunar_crystal_ingredients',
      'eternal_starlight:red_starlight_crystal_shard',
      '#eternal_starlight:lunar_crystal_ingredients',
      'eternal_starlight:red_starlight_crystal_shard',
      '#eternal_starlight:lunar_crystal_ingredients',
    ],
    'eternal_starlight:red_starlight_crystal_shard',
    'eternal_starlight:lunar_crystal',
    10000,
  );

  event.recipes.ars_nouveau.enchanting_apparatus(
    [
      'eternal_starlight:red_starlight_crystal_shard',
      '#eternal_starlight:water_crystal_ingredients',
      'eternal_starlight:red_starlight_crystal_shard',
      '#eternal_starlight:water_crystal_ingredients',
      'eternal_starlight:red_starlight_crystal_shard',
      '#eternal_starlight:water_crystal_ingredients',
      'eternal_starlight:red_starlight_crystal_shard',
      '#eternal_starlight:water_crystal_ingredients',
    ],
    'eternal_starlight:red_starlight_crystal_shard',
    'eternal_starlight:water_crystal',
    10000,
  );

  event.recipes.ars_nouveau.enchanting_apparatus(
    [
      'eternal_starlight:red_starlight_crystal_shard',
      '#eternal_starlight:light_crystal_ingredients',
      'eternal_starlight:red_starlight_crystal_shard',
      '#eternal_starlight:light_crystal_ingredients',
      'eternal_starlight:red_starlight_crystal_shard',
      '#eternal_starlight:light_crystal_ingredients',
      'eternal_starlight:red_starlight_crystal_shard',
      '#eternal_starlight:light_crystal_ingredients',
    ],
    'eternal_starlight:red_starlight_crystal_shard',
    'eternal_starlight:light_crystal',
    10000,
  );
});
