ServerEvents.recipes((event) => {
  event.recipes.ars_nouveau.enchanting_apparatus(
    [
      'malum:cthonic_gold',
      'hazennstuff:deus_essence',
      'malum:cthonic_gold',
      'hazennstuff:deus_essence',
      'malum:cthonic_gold',
      'hazennstuff:deus_essence',
      'malum:cthonic_gold',
      'hazennstuff:deus_essence',
    ],
    'ars_nouveau:drygmy_shard',
    'ars_nouveau:drygmy_charm',
    20000,
  );
  event.recipes.ars_nouveau.enchanting_apparatus(
    [
      'create:golden_sheet',
      'create:golden_sheet',
      'ars_nouveau:source_gem_block',
      'createaddition:iron_rod',
      'create:golden_sheet',
      'createaddition:iron_rod',
      'ars_nouveau:source_gem_block',
      'create:golden_sheet',
    ],
    'create:potato_cannon',
    'ars_nouveau:splash_flask_cannon',
    2000,
  );
  event.recipes.ars_nouveau.enchanting_apparatus(
    [
      'malum:warp_flux',
      'royalvariations:royal_ender_pearl',
      'malum:warp_flux',
      'royalvariations:royal_ender_pearl',
      'malum:warp_flux',
      'royalvariations:royal_ender_pearl',
      'malum:warp_flux',
      'royalvariations:royal_ender_pearl',
    ],
    'ars_nouveau:warp_scroll',
    'ars_nouveau:stable_warp_scroll',
    10000,
  );
  event.recipes.ars_nouveau.enchanting_apparatus(
    [
      'ars_elemental:mark_of_mastery',
      'ars_elemental:mark_of_mastery',
      'eternal_starlight:wind_crystal',
      'eternal_starlight:terra_crystal',
      'irons_spellbooks:divine_soulshard',
      'eternal_starlight:blaze_crystal',
      'eternal_starlight:water_crystal',
      'ars_elemental:mark_of_mastery',
    ],
    'ars_nouveau:apprentice_spell_book',
    'ars_nouveau:archmage_spell_book',
    20000,
  );
});
