// recipes/global/remove.js
ServerEvents.recipes((event) => {
  const recipes = [
    // ae2
    { id: 'ae2:inscriber/logic_processor' },
    { id: 'ae2:inscriber/calculation_processor' },
    { id: 'ae2:inscriber/engineering_processor' },
    { id: 'ae2:inscriber/controller' },
    { id: 'ae2:inscriber/energy_acceptor' },
    { id: 'ae2:inscriber/quartz_glass' },
    { id: 'ae2:network/cells/spatial_components' },
    { id: 'ae2:network/cells/4k' },
    { id: 'ae2:network/cells/16k' },
    { id: 'ae2:network/cells/64k' },
    { id: 'ae2:network/cells/256k' },
    { id: 'ae2:network/cells/spatial_2' },
    { id: 'ae2:network/cells/spatial_16' },
    { id: 'ae2:network/cells/spatial_128' },
    { id: 'ae2:network/blocks/inscribers' },
    { id: 'ae2:materials/formationcore' },
    { id: 'ae2:materials/annihilationcore' },
    { id: 'ae2:network/cables/glass_fluix' },
    { id: 'ae2:network/parts/quartz_fiber_part' },
    { id: 'ae2:decorative/quartz_vibrant_glass' },
    { id: 'ae2:inscriber/silicon_print' },
    { id: 'ae2:inscriber/logic_processor_print' },

    // aeinfinitybooster
    { id: 'aeinfinitybooster:infinity_card' },

    // arseng
    { id: 'arseng:source_cell_housing' },

    // extendedae
    { id: 'extendedae:inscriber/concurrent_process' },
    { id: 'extendedae:crystal_assembler' },
    { id: 'extendedae:assembler_matrix_frame' },
    { id: 'extendedae:entro_seed' },

    // create diesel generators
    { id: 'createdieselgenerators:bulk_fermenting/fermentable' },
    { id: 'createdieselgenerators:basin_fermenting/fermentable' },
    { id: 'createdieselgenerators:compacting/plant_oil' },

    // create additions
    { id: 'createaddition:liquid_burning/biofuel' },
    { id: 'createaddition:mixing/bioethanol' },

    // oritech
    { id: 'oritech:centrifuge/fluid/plasticoilbetter' },
    { id: 'oritech:foundry/alloy/steel' },
    { id: 'oritech:biosteel_blockblockinv' },
    { id: 'oritech:crafting/alloy/steel' },
    { id: 'oritech:refinery/wood' },
    { id: 'oritech:foundry/alloy/electrum' },
    { id: 'oritech:mixing/compat/create/electrum' },
    { id: 'oritech:crafting/alloy/electrum' },
    { id: 'oritech:mixing/compat/create/steel' },
    { id: 'oritech:foundry/alloy/adamant' },
    { id: 'oritech:foundry/alloy/biosteel' },
    { id: 'oritech:crafting/alloy/adamant' },
    { id: 'oritech:centrifuge/fluid/siliconwash' },
    { id: 'oritech:centrifuge/fluid/siliconwashbad' },
    { id: 'oritech:crafting/alloy/rawsilicon' },
    { id: 'oritech:silicon_from_smelting_raw_silicon' },
    { id: 'oritech:refinery/siliconwashing' },

    // ars_nouveau
    { id: 'ars_elemental:imbuement_anima_essence' },
    { id: 'ars_nouveau:imbuement_water_essence' },
    { id: 'ars_nouveau:imbuement_manipulation_essence' },
    { id: 'ars_nouveau:imbuement_abjuration_essence' },
    { id: 'ars_nouveau:imbuement_conjuration_essence' },
    { id: 'ars_nouveau:imbuement_fire_essence' },
    { id: 'ars_nouveau:imbuement_air_essence' },
    { id: 'ars_nouveau:imbuement_earth_essence' },
    { id: 'ars_nouveau:arcane_pedestal' },
    { id: 'ars_nouveau:arcane_core' },
    { id: 'ars_nouveau:enchanting_apparatus' },
    { id: 'ars_nouveau:imbuement_chamber' },
    { id: 'ars_nouveau:source_jar' },
    { id: 'ars_nouveau:warp_scroll' },
    { id: 'ars_nouveau:stable_warp_scroll' },
    { id: 'ars_nouveau:dull_trinket' },
    { id: 'ars_nouveau:amulet_of_mana_boost' },
    { id: 'ars_nouveau:amulet_of_mana_regen' },
    { id: 'ars_nouveau:mundane_belt' },
    { id: 'ars_nouveau:ring_of_potential' },
    { id: 'ars_nouveau:drygmy_charm' },
    { id: 'ars_nouveau:novice_spell_book' },
    { id: 'ars_nouveau:novice_spellbook_alt' },
    { id: 'ars_nouveau:archmage_book_upgrade' },

    // irons_spellbooks
    { id: 'irons_spellbooks:ender_rune' },
    { id: 'irons_spellbooks:evocation_rune' },
    { id: 'irons_spellbooks:fire_rune' },
    { id: 'irons_spellbooks:holy_rune' },
    { id: 'irons_spellbooks:ice_rune' },
    { id: 'irons_spellbooks:lightning_rune' },
    { id: 'irons_spellbooks:nature_rune' },
    { id: 'irons_spellbooks:blood_rune' },
    { id: 'irons_spellbooks:shriving_stone' },
    { id: 'irons_spellbooks:iron_spell_book' },
    { id: 'irons_spellbooks:portal_frame' },
    { id: 'irons_spellbooks:inscription_table' },

    // apotheosis
    { id: 'apotheosis:simple_reforging_table' },
    { id: 'apotheosis:reforging_table' },

    // hazennstuff
    { id: 'hazennstuff:crafting/materials/starkissed_zenalite' },
    { id: 'hazennstuff:crafting/materials/deus_essence_from_divine_soulshard' },
    { id: 'hazennstuff:smelting/blasting/zenalite_from_blasting_starkissed_zenalite' },
    { id: 'hazennstuff:crafting/armor/miner/miner_helmet' },
    { id: 'hazennstuff:crafting/armor/miner/miner_chestplate' },
    { id: 'hazennstuff:crafting/armor/miner/miner_leggings' },
    { id: 'hazennstuff:crafting/armor/miner/miner_boots' },
    { id: 'hazennstuff:crafting/armor/blazeborne/blazeborne_helmet' },
    { id: 'hazennstuff:crafting/armor/blazeborne/blazeborne_chestplate' },
    { id: 'hazennstuff:crafting/armor/blazeborne/blazeborne_leggings' },
    { id: 'hazennstuff:crafting/armor/blazeborne/blazeborne_boots' },
    { id: 'hazennstuff:crafting/armor/seraph/seraph_helmet' },
    { id: 'hazennstuff:crafting/armor/seraph/seraph_chestplate' },
    { id: 'hazennstuff:crafting/armor/seraph/seraph_leggings' },
    { id: 'hazennstuff:crafting/armor/seraph/seraph_boots' },
    { id: 'hazennstuff:crafting/armor/cryogenic_ruler/cryogenic_ruler_helmet' },
    { id: 'hazennstuff:crafting/armor/cryogenic_ruler/cryogenic_ruler_chestplate' },
    { id: 'hazennstuff:crafting/armor/cryogenic_ruler/cryogenic_ruler_leggings' },
    { id: 'hazennstuff:crafting/armor/cryogenic_ruler/cryogenic_ruler_boots' },
    { id: 'hazennstuff:crafting/armor/charged_scourge/charged_scourge_helmet' },
    { id: 'hazennstuff:crafting/armor/charged_scourge/charged_scourge_chestplate' },
    { id: 'hazennstuff:crafting/armor/charged_scourge/charged_scourge_leggings' },
    { id: 'hazennstuff:crafting/armor/charged_scourge/charged_scourge_boots' },
    { id: 'hazennstuff:crafting/armor/flesh_mass/flesh_mass_helmet' },
    { id: 'hazennstuff:crafting/armor/flesh_mass/flesh_mass_chestplate' },
    { id: 'hazennstuff:crafting/armor/flesh_mass/flesh_mass_leggings' },
    { id: 'hazennstuff:crafting/armor/flesh_mass/flesh_mass_boots' },
    { id: 'hazennstuff:crafting/armor/creaking/creaking_helmet' },
    { id: 'hazennstuff:crafting/armor/creaking/creaking_chestplate' },
    { id: 'hazennstuff:crafting/armor/creaking/creaking_leggings' },
    { id: 'hazennstuff:crafting/armor/creaking/creaking_boots' },
    { id: 'hazennstuff:crafting/armor/ender_dragon/ender_dragon_helmet' },
    { id: 'hazennstuff:crafting/armor/ender_dragon/ender_dragon_chestplate' },
    { id: 'hazennstuff:crafting/armor/ender_dragon/ender_dragon_leggings' },
    { id: 'hazennstuff:crafting/armor/ender_dragon/ender_dragon_boots' },
    { id: 'hazennstuff:crafting/armor/alchemist_supreme/alchemist_supreme_helmet' },
    { id: 'hazennstuff:crafting/armor/alchemist_supreme/alchemist_supreme_chestplate' },
    { id: 'hazennstuff:crafting/armor/alchemist_supreme/alchemist_supreme_leggings' },
    { id: 'hazennstuff:crafting/armor/alchemist_supreme/alchemist_supreme_boots' },

    // crystal_chronicles
    { id: 'minecraft:paladin_helmet_smithing' },
    { id: 'minecraft:paladin_chestplate_smithing' },
    { id: 'minecraft:paladin_leggings_smithing' },
    { id: 'minecraft:paladin_boots_smithing' },
    { id: 'minecraft:tank_helmet_smithing' },
    { id: 'minecraft:tank_chestplate_smithing ' },
    { id: 'minecraft:tank_leggings_smithing' },
    { id: 'minecraft:tank_boots_smithing' },
    { id: 'minecraft:pyromancer_helmet_smithing' },
    { id: 'minecraft:pyromancer_chestplate_smithing' },
    { id: 'minecraft:pyromancer_leggings_smithing' },
    { id: 'minecraft:pyromancer_boots_smithing' },
    { id: 'minecraft:mage_helmet_smithing' },
    { id: 'minecraft:mage_chestplate_smithing' },
    { id: 'minecraft:mage_leggings_smithing' },
    { id: 'minecraft:mage_boots_smithing' },
    { id: 'minecraft:toxic_helmet_smithing' },
    { id: 'minecraft:toxic_chestplate_smithing' },
    { id: 'minecraft:toxic_leggings_smithing' },
    { id: 'minecraft:toxic_boots_smithing' },
    { id: 'minecraft:electromancer_helmet_smithing' },
    { id: 'minecraft:electromancer_chestplate_smithing' },
    { id: 'minecraft:electromancer_leggings_smithing' },
    { id: 'minecraft:electromancer_boots_smithing' },
    { id: 'minecraft:rogue_helmet_smithing' },
    { id: 'minecraft:rogue_chestplate_smithing' },
    { id: 'minecraft:rogue_leggings_smithing' },
    { id: 'minecraft:rogue_boots_smithing' },
    { id: 'crystal_chronicles:paladin_sword' },
    { id: 'crystal_chronicles:ice_hammer' },
    { id: 'crystal_chronicles:staff' },
    { id: 'crystal_chronicles:blood_scythe' },
    { id: 'crystal_chronicles:spear' },
    { id: 'crystal_chronicles:lightning_bident' },
    { id: 'crystal_chronicles:chakram' },
    { id: 'crystal_chronicles:paladin_shield' },
    { id: 'crystal_chronicles:evocation_twinblade' },
    { id: 'crystal_chronicles:hemalite_shard' },
    { id: 'crystal_chronicles:ice_shard' },
    { id: 'crystal_chronicles:floralite_shard' },
    { id: 'crystal_chronicles:divinite_shard' },
    { id: 'crystal_chronicles:voidstone_shard' },
    { id: 'crystal_chronicles:voltite_shard' },
    { id: 'crystal_chronicles:volcanite_shard' },

    // cataclysm
    { id: 'cataclysm:smithing/ignitium_helmet' },
    { id: 'cataclysm:smithing/ignitium_chestplate' },
    { id: 'cataclysm:smithing/ignitium_leggings' },
    { id: 'cataclysm:smithing/ignitium_boots' },
    { id: 'cataclysm:smithing/cursium_helmet' },
    { id: 'cataclysm:smithing/cursium_chestplate' },
    { id: 'cataclysm:smithing/cursium_leggings' },
    { id: 'cataclysm:smithing/cursium_boots' },

    // gateways
    { id: 'gateways:basic/blaze' },
    { id: 'gateways:basic/enderman' },
    { id: 'gateways:emerald_grove' },
    { id: 'gateways:endless/blaze' },
    { id: 'gateways:overworldian_nights' },
    { id: 'gateways:hellish_fortress' },

    // simplyswords
    { id: 'simplyswords:runic_longsword' },
    { id: 'simplyswords:runic_twinblade' },
    { id: 'simplyswords:runic_rapier' },
    { id: 'simplyswords:runic_cutlass' },
    { id: 'simplyswords:runic_greataxe' },
    { id: 'simplyswords:runic_chakram' },
    { id: 'simplyswords:runic_greathammer' },
    { id: 'simplyswords:runic_scythe' },
    { id: 'simplyswords:runic_sai' },
    { id: 'simplyswords:runic_glaive' },
    { id: 'simplyswords:runic_warglaive' },
    { id: 'simplyswords:runic_halberd' },
    { id: 'simplyswords:runic_spear' },
    { id: 'simplyswords:runic_katana' },
    { id: 'simplyswords:runic_claymore' },
    { id: 'simplyswords:tainted_relic' },
    { id: 'simplyswords:righteous_relic' },
    { id: 'simplyswords:sunfire' },
    { id: 'simplyswords:harbinger' },
    { id: 'simplyswords:waking_lichblade' },
    { id: 'simplyswords:awakened_lichblade' },
    { id: 'simplyswords:runefused_gem' },
    { id: 'simplyswords:netherfused_gem' },

    // eidolon_repraised
    { id: 'eidolon_repraised:worktable' },
    { id: 'eidolon_repraised:arcane_gold_ingot' },
    { id: 'eidolon_repraised:arcane_gold_nugget' },
    { id: 'eidolon_repraised:arcane_gold_block' },

    // iceandfire
    { id: 'iceandfire:dragonforge_lightning_core_disabled' },
    { id: 'iceandfire:dragonforge_ice_core_disabled' },
    { id: 'iceandfire:dragonforge_fire_core_disabled' },
    { id: 'iceandfire:dragonforge_lightning_input' },
    { id: 'iceandfire:dragonforge_fire_input' },
    { id: 'iceandfire:dragonforge_ice_input' },
    { id: 'iceandfire:summoning_crystal_ice' },
    { id: 'iceandfire:summoning_crystal_fire' },
    { id: 'iceandfire:summoning_crystal_lightning' },
    { id: 'iceandfire:dragonforge/dragonsteel_lightning_ingot' },
    { id: 'iceandfire:dragonforge/dragonsteel_fire_ingot' },
    { id: 'iceandfire:dragonforge/dragonsteel_ice_ingot' },

    // immersive_aircraft
    { id: 'immersive_aircraft:airship' },
    { id: 'immersive_aircraft:biplane' },
    { id: 'immersive_aircraft:warship' },
    { id: 'immersive_aircraft:propeller' },
    { id: 'immersive_aircraft:enhanced_propeller' },
    { id: 'immersive_aircraft:steel_boiler' },
    { id: 'immersive_aircraft:gyroscope' },
    { id: 'immersive_aircraft:hull' },
    { id: 'immersive_aircraft:sail' },
    { id: 'immersive_aircraft:engine' },
    { id: 'immersive_aircraft:quadrocopter' },
    { id: 'immersive_aircraft:nether_engine' },
    { id: 'immersive_aircraft:eco_engine' },
    { id: 'immersive_aircraft:industrial_gears' },

    // eternal_starlight
    { id: 'eternal_starlight:terra_crystal' },
    { id: 'eternal_starlight:wind_crystal' },
    { id: 'eternal_starlight:water_crystal' },
    { id: 'eternal_starlight:lunar_crystal' },
    { id: 'eternal_starlight:blaze_crystal' },
    { id: 'eternal_starlight:light_crystal' },

    // naturescompass
    { id: 'naturescompass:natures_compass' },

    // malum
    { id: 'malum:malignant_pewter_plating' },
    { id: 'malum:soul_stained_steel_plating' },

    // minecraft
    { id: 'minecraft:copper_trapdoor' },

    // create
    { id: 'createaddition:crushing/tuff_recycling' },
    { id: 'create:item_application/railway_casing' },

    // sophisticatedstorage
    { id: 'sophisticatedstorage:controller' },

    // by other mods, not mine
    { id: 'ends_delight:food/ender_noodle' },
  ];

  recipes.forEach((recipe) => {
    event.remove(recipe);
  });
});
