ServerEvents.recipes((event) => {
  const recipes = [
    { id: 'crystal_chronicles:paladin_sword' },
    { id: 'crystal_chronicles:ice_hammer' },
    { id: 'crystal_chronicles:staff' },
    { id: 'crystal_chronicles:blood_scythe' },
    { id: 'crystal_chronicles:spear' },
    { id: 'crystal_chronicles:lightning_bident' },
    { id: 'crystal_chronicles:chakram' },
    { id: 'crystal_chronicles:paladin_shield' },
    { id: 'crystal_chronicles:evocation_twinblade' },
    { id: 'crystal_chronicles:hemalite_shard' },
    { id: 'crystal_chronicles:ice_shard' },
    { id: 'crystal_chronicles:floralite_shard' },
    { id: 'crystal_chronicles:divinite_shard' },
    { id: 'crystal_chronicles:voidstone_shard' },
    { id: 'crystal_chronicles:voltite_shard' },
    { id: 'crystal_chronicles:volcanite_shard' },
    { id: 'minecraft:paladin_helmet_smithing' },
    { id: 'minecraft:paladin_chestplate_smithing' },
    { id: 'minecraft:paladin_leggings_smithing' },
    { id: 'minecraft:paladin_boots_smithing' },
    { id: 'minecraft:tank_helmet_smithing' },
    { id: 'minecraft:tank_chestplate_smithing' },
    { id: 'minecraft:tank_leggings_smithing' },
    { id: 'minecraft:tank_boots_smithing' },
    { id: 'minecraft:pyromancer_helmet_smithing' },
    { id: 'minecraft:pyromancer_chestplate_smithing' },
    { id: 'minecraft:pyromancer_leggings_smithing' },
    { id: 'minecraft:pyromancer_boots_smithing' },
    { id: 'minecraft:mage_helmet_smithing' },
    { id: 'minecraft:mage_chestplate_smithing' },
    { id: 'minecraft:mage_leggings_smithing' },
    { id: 'minecraft:mage_boots_smithing' },
    { id: 'minecraft:toxic_helmet_smithing' },
    { id: 'minecraft:toxic_chestplate_smithing' },
    { id: 'minecraft:toxic_leggings_smithing' },
    { id: 'minecraft:toxic_boots_smithing' },
    { id: 'minecraft:electromancer_helmet_smithing' },
    { id: 'minecraft:electromancer_chestplate_smithing' },
    { id: 'minecraft:electromancer_leggings_smithing' },
    { id: 'minecraft:electromancer_boots_smithing' },
    { id: 'minecraft:rogue_helmet_smithing' },
    { id: 'minecraft:rogue_chestplate_smithing' },
    { id: 'minecraft:rogue_leggings_smithing' },
    { id: 'minecraft:rogue_boots_smithing' },
  ];

  recipes.forEach((recipe) => {
    event.remove(recipe);
  });
});
