ServerEvents.recipes((event) => {
  const id_prefix = 'mt:crystal_chronicles/spirit_infusion/';

  const recipes = [
    // Paladin Armor (Sacred)
    {
      result: { id: 'crystal_chronicles:paladin_helmet', count: 1 },
      input: { item: 'irons_spellbooks:priest_helmet', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:divinite_shard' },
        { item: 'royalvariations:royal_armor_fragments', count: 4 },
      ],
      spirits: [{ type: 'malum:sacred', count: 64 }],
      id: `${id_prefix}paladin_helmet`,
    },
    {
      result: { id: 'crystal_chronicles:paladin_chestplate', count: 1 },
      input: { item: 'irons_spellbooks:priest_chestplate', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:divinite_shard' },
        { item: 'royalvariations:royal_armor_fragments', count: 4 },
      ],
      spirits: [{ type: 'malum:sacred', count: 64 }],
      id: `${id_prefix}paladin_chestplate`,
    },
    {
      result: { id: 'crystal_chronicles:paladin_leggings', count: 1 },
      input: { item: 'irons_spellbooks:priest_leggings', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:divinite_shard' },
        { item: 'royalvariations:royal_armor_fragments', count: 4 },
      ],
      spirits: [{ type: 'malum:sacred', count: 64 }],
      id: `${id_prefix}paladin_leggings`,
    },
    {
      result: { id: 'crystal_chronicles:paladin_boots', count: 1 },
      input: { item: 'irons_spellbooks:priest_boots', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:divinite_shard' },
        { item: 'royalvariations:royal_armor_fragments', count: 4 },
      ],
      spirits: [{ type: 'malum:sacred', count: 64 }],
      id: `${id_prefix}paladin_boots`,
    },
    // Tank Armor (Aqueous)
    {
      result: { id: 'crystal_chronicles:tank_helmet', count: 1 },
      input: { item: 'irons_spellbooks:cryomancer_helmet', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:ice_shard' },
        { item: 'royalvariations:royal_armor_fragments', count: 4 },
      ],
      spirits: [{ type: 'malum:aqueous', count: 64 }],
      id: `${id_prefix}tank_helmet`,
    },
    {
      result: { id: 'crystal_chronicles:tank_chestplate', count: 1 },
      input: { item: 'irons_spellbooks:cryomancer_chestplate', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:ice_shard' },
        { item: 'royalvariations:royal_armor_fragments', count: 4 },
      ],
      spirits: [{ type: 'malum:aqueous', count: 64 }],
      id: `${id_prefix}tank_chestplate`,
    },
    {
      result: { id: 'crystal_chronicles:tank_leggings', count: 1 },
      input: { item: 'irons_spellbooks:cryomancer_leggings', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:ice_shard' },
        { item: 'royalvariations:royal_armor_fragments', count: 4 },
      ],
      spirits: [{ type: 'malum:aqueous', count: 64 }],
      id: `${id_prefix}tank_leggings`,
    },
    {
      result: { id: 'crystal_chronicles:tank_boots', count: 1 },
      input: { item: 'irons_spellbooks:cryomancer_boots', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:ice_shard' },
        { item: 'royalvariations:royal_armor_fragments', count: 4 },
      ],
      spirits: [{ type: 'malum:aqueous', count: 64 }],
      id: `${id_prefix}tank_boots`,
    },
    // Pyromancer Armor (Infernal)
    {
      result: { id: 'crystal_chronicles:pyromancer_helmet', count: 1 },
      input: { item: 'irons_spellbooks:pyromancer_helmet', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:volcanite_shard' },
        { item: 'royalvariations:royal_armor_fragments', count: 4 },
      ],
      spirits: [{ type: 'malum:infernal', count: 64 }],
      id: `${id_prefix}pyromancer_helmet`,
    },
    {
      result: { id: 'crystal_chronicles:pyromancer_chestplate', count: 1 },
      input: { item: 'irons_spellbooks:pyromancer_chestplate', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:volcanite_shard' },
        { item: 'royalvariations:royal_armor_fragments', count: 4 },
      ],
      spirits: [{ type: 'malum:infernal', count: 64 }],
      id: `${id_prefix}pyromancer_chestplate`,
    },
    {
      result: { id: 'crystal_chronicles:pyromancer_leggings', count: 1 },
      input: { item: 'irons_spellbooks:pyromancer_leggings', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:volcanite_shard' },
        { item: 'royalvariations:royal_armor_fragments', count: 4 },
      ],
      spirits: [{ type: 'malum:infernal', count: 64 }],
      id: `${id_prefix}pyromancer_leggings`,
    },
    {
      result: { id: 'crystal_chronicles:pyromancer_boots', count: 1 },
      input: { item: 'irons_spellbooks:pyromancer_boots', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:volcanite_shard' },
        { item: 'royalvariations:royal_armor_fragments', count: 4 },
      ],
      spirits: [{ type: 'malum:infernal', count: 64 }],
      id: `${id_prefix}pyromancer_boots`,
    },
    // Mage Armor (Eldritch)
    {
      result: { id: 'crystal_chronicles:mage_helmet', count: 1 },
      input: { item: 'irons_spellbooks:shadowwalker_helmet', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:voidstone_shard' },
        { item: 'royalvariations:royal_armor_fragments', count: 4 },
      ],
      spirits: [{ type: 'malum:eldritch', count: 64 }],
      id: `${id_prefix}mage_helmet`,
    },
    {
      result: { id: 'crystal_chronicles:mage_chestplate', count: 1 },
      input: { item: 'irons_spellbooks:shadowwalker_chestplate', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:voidstone_shard' },
        { item: 'royalvariations:royal_armor_fragments', count: 4 },
      ],
      spirits: [{ type: 'malum:eldritch', count: 64 }],
      id: `${id_prefix}mage_chestplate`,
    },
    {
      result: { id: 'crystal_chronicles:mage_leggings', count: 1 },
      input: { item: 'irons_spellbooks:shadowwalker_leggings', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:voidstone_shard' },
        { item: 'royalvariations:royal_armor_fragments', count: 4 },
      ],
      spirits: [{ type: 'malum:eldritch', count: 64 }],
      id: `${id_prefix}mage_leggings`,
    },
    {
      result: { id: 'crystal_chronicles:mage_boots', count: 1 },
      input: { item: 'irons_spellbooks:shadowwalker_boots', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:voidstone_shard' },
        { item: 'royalvariations:royal_armor_fragments', count: 4 },
      ],
      spirits: [{ type: 'malum:eldritch', count: 64 }],
      id: `${id_prefix}mage_boots`,
    },
    // Toxic Armor (Earthen)
    {
      result: { id: 'crystal_chronicles:toxic_helmet', count: 1 },
      input: { item: 'irons_spellbooks:plagued_helmet', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:floralite_shard' },
        { item: 'royalvariations:royal_armor_fragments', count: 4 },
      ],
      spirits: [{ type: 'malum:earthen', count: 64 }],
      id: `${id_prefix}toxic_helmet`,
    },
    {
      result: { id: 'crystal_chronicles:toxic_chestplate', count: 1 },
      input: { item: 'irons_spellbooks:plagued_chestplate', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:floralite_shard' },
        { item: 'royalvariations:royal_armor_fragments', count: 4 },
      ],
      spirits: [{ type: 'malum:earthen', count: 64 }],
      id: `${id_prefix}toxic_chestplate`,
    },
    {
      result: { id: 'crystal_chronicles:toxic_leggings', count: 1 },
      input: { item: 'irons_spellbooks:plagued_leggings', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:floralite_shard' },
        { item: 'royalvariations:royal_armor_fragments', count: 4 },
      ],
      spirits: [{ type: 'malum:earthen', count: 64 }],
      id: `${id_prefix}toxic_leggings`,
    },
    {
      result: { id: 'crystal_chronicles:toxic_boots', count: 1 },
      input: { item: 'irons_spellbooks:plagued_boots', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:floralite_shard' },
        { item: 'royalvariations:royal_armor_fragments', count: 4 },
      ],
      spirits: [{ type: 'malum:earthen', count: 64 }],
      id: `${id_prefix}toxic_boots`,
    },
    // Electromancer Armor (Aerial)
    {
      result: { id: 'crystal_chronicles:electromancer_helmet', count: 1 },
      input: { item: 'irons_spellbooks:electromancer_helmet', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:voltite_shard' },
        { item: 'royalvariations:royal_armor_fragments', count: 4 },
      ],
      spirits: [{ type: 'malum:aerial', count: 64 }],
      id: `${id_prefix}electromancer_helmet`,
    },
    {
      result: { id: 'crystal_chronicles:electromancer_chestplate', count: 1 },
      input: { item: 'irons_spellbooks:electromancer_chestplate', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:voltite_shard' },
        { item: 'royalvariations:royal_armor_fragments', count: 4 },
      ],
      spirits: [{ type: 'malum:aerial', count: 64 }],
      id: `${id_prefix}electromancer_chestplate`,
    },
    {
      result: { id: 'crystal_chronicles:electromancer_leggings', count: 1 },
      input: { item: 'irons_spellbooks:electromancer_leggings', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:voltite_shard' },
        { item: 'royalvariations:royal_armor_fragments', count: 4 },
      ],
      spirits: [{ type: 'malum:aerial', count: 64 }],
      id: `${id_prefix}electromancer_leggings`,
    },
    {
      result: { id: 'crystal_chronicles:electromancer_boots', count: 1 },
      input: { item: 'irons_spellbooks:electromancer_boots', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:voltite_shard' },
        { item: 'royalvariations:royal_armor_fragments', count: 4 },
      ],
      spirits: [{ type: 'malum:aerial', count: 64 }],
      id: `${id_prefix}electromancer_boots`,
    },
    // Rogue Armor (Wicked)
    {
      result: { id: 'crystal_chronicles:rogue_helmet', count: 1 },
      input: { item: 'irons_spellbooks:cultist_helmet', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:hemalite_shard' },
        { item: 'royalvariations:royal_armor_fragments', count: 4 },
      ],
      spirits: [{ type: 'malum:wicked', count: 64 }],
      id: `${id_prefix}rogue_helmet`,
    },
    {
      result: { id: 'crystal_chronicles:rogue_chestplate', count: 1 },
      input: { item: 'irons_spellbooks:cultist_chestplate', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:hemalite_shard' },
        { item: 'royalvariations:royal_armor_fragments', count: 4 },
      ],
      spirits: [{ type: 'malum:wicked', count: 64 }],
      id: `${id_prefix}rogue_chestplate`,
    },
    {
      result: { id: 'crystal_chronicles:rogue_leggings', count: 1 },
      input: { item: 'irons_spellbooks:cultist_leggings', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:hemalite_shard' },
        { item: 'royalvariations:royal_armor_fragments', count: 4 },
      ],
      spirits: [{ type: 'malum:wicked', count: 64 }],
      id: `${id_prefix}rogue_leggings`,
    },
    {
      result: { id: 'crystal_chronicles:rogue_boots', count: 1 },
      input: { item: 'irons_spellbooks:cultist_boots', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:hemalite_shard' },
        { item: 'royalvariations:royal_armor_fragments', count: 4 },
      ],
      spirits: [{ type: 'malum:wicked', count: 64 }],
      id: `${id_prefix}rogue_boots`,
    },
    {
      result: { id: 'crystal_chronicles:volcanite_shard', count: 1 },
      input: { item: 'irons_spellbooks:divine_soulshard', count: 1 },
      extraInputs: [{ item: 'ars_nouveau:fire_essence', count: 64 }],
      spirits: [{ type: 'malum:infernal', count: 64 }],
      id: `${id_prefix}volcanite_shard`,
    },
    {
      result: { id: 'crystal_chronicles:ice_shard', count: 1 },
      input: { item: 'irons_spellbooks:divine_soulshard', count: 1 },
      extraInputs: [{ item: 'kubejs:ice_essence', count: 64 }],
      spirits: [{ type: 'malum:aqueous', count: 64 }],
      id: `${id_prefix}ice_shard`,
    },
    {
      result: { id: 'crystal_chronicles:divinite_shard', count: 1 },
      input: { item: 'irons_spellbooks:divine_soulshard', count: 1 },
      extraInputs: [{ item: 'ars_nouveau:manipulation_essence', count: 64 }],
      spirits: [{ type: 'malum:sacred', count: 64 }],
      id: `${id_prefix}divinite_shard`,
    },
    {
      result: { id: 'crystal_chronicles:floralite_shard', count: 1 },
      input: { item: 'irons_spellbooks:divine_soulshard', count: 1 },
      extraInputs: [{ item: 'ars_nouveau:earth_essence', count: 64 }],
      spirits: [{ type: 'malum:earthen', count: 64 }],
      id: `${id_prefix}floralite_shard`,
    },
    {
      result: { id: 'crystal_chronicles:voltite_shard', count: 1 },
      input: { item: 'irons_spellbooks:divine_soulshard', count: 1 },
      extraInputs: [{ item: 'ars_nouveau:air_essence', count: 64 }],
      spirits: [{ type: 'malum:aerial', count: 64 }],
      id: `${id_prefix}voltite_shard`,
    },
    {
      result: { id: 'crystal_chronicles:voidstone_shard', count: 1 },
      input: { item: 'irons_spellbooks:divine_soulshard', count: 1 },
      extraInputs: [{ item: 'ars_nouveau:abjuration_essence', count: 64 }],
      spirits: [{ type: 'malum:eldritch', count: 64 }],
      id: `${id_prefix}voidstone_shard`,
    },
    {
      result: { id: 'crystal_chronicles:hemalite_shard', count: 1 },
      input: { item: 'irons_spellbooks:divine_soulshard', count: 1 },
      extraInputs: [{ item: 'ars_elemental:anima_essence', count: 64 }],
      spirits: [{ type: 'malum:wicked', count: 64 }],
      id: `${id_prefix}hemalite_shard`,
    },
  ];

  recipes.forEach((recipe) => {
    recipe.type = 'malum:spirit_infusion';
    event.custom(recipe).id(recipe.id);
  });
});
