// EMNTITIES
ServerEvents.tags('entity_type', (event) => {
  event.add('ars_nouveau:jar_blacklist', [
    // ars_nouveau
    'ars_nouveau:alakarkinos',
    'ars_nouveau:drygmy',
    'ars_nouveau:starbuncle',
    'ars_nouveau:whirlisprig',
    'ars_nouveau:wilden_guardian',
    'ars_nouveau:wilden_hunter',
    'ars_nouveau:wilden_stalker',

    // cataclysm
    'cataclysm:amethyst_crab',
    'cataclysm:ancient_remnant',
    'cataclysm:aptrgangr',
    'cataclysm:cindaria',
    'cataclysm:clawdian',
    'cataclysm:coral_golem',
    'cataclysm:coralssus',
    'cataclysm:deepling',
    'cataclysm:deepling_angler',
    'cataclysm:deepling_brute',
    'cataclysm:deepling_priest',
    'cataclysm:deepling_warlock',
    'cataclysm:elite_draugr',
    'cataclysm:ender_golem',
    'cataclysm:ender_guardian',
    'cataclysm:endermaptera',
    'cataclysm:ignis',
    'cataclysm:ignited_berserker',
    'cataclysm:ignited_revenant',
    'cataclysm:kobolediator',
    'cataclysm:koboleton',
    'cataclysm:maledictus',
    'cataclysm:modern_remnant',
    'cataclysm:netherite_ministrosity',
    'cataclysm:netherite_monstrosity',
    'cataclysm:octohost',
    'cataclysm:royal_draugr',
    'cataclysm:scylla',
    'cataclysm:symbiocto',
    'cataclysm:the_baby_leviathan',
    'cataclysm:the_harbinger',
    'cataclysm:the_leviathan',
    'cataclysm:the_prowler',
    'cataclysm:the_watcher',
    'cataclysm:urchinkin',

    // enchantwithmob
    'enchantwithmob:enchanter',

    // eternal_starlight
    'eternal_starlight:aethersent_golem',
    'eternal_starlight:astral_golem',
    'eternal_starlight:aurora_deer',
    'eternal_starlight:creteor',
    'eternal_starlight:flare_spawner',
    'eternal_starlight:freeze_spawner',
    'eternal_starlight:gleech',
    'eternal_starlight:grimstone_golem',
    'eternal_starlight:lonestar_skeleton',
    'eternal_starlight:luminaris',
    'eternal_starlight:luminofish',
    'eternal_starlight:lunar_monstrosity',
    'eternal_starlight:permafrost',
    'eternal_starlight:rookfish',
    'eternal_starlight:seeker',
    'eternal_starlight:shadow_snail',
    'eternal_starlight:shimmer_lacewing',
    'eternal_starlight:starlight_golem',
    'eternal_starlight:stranghoul',
    'eternal_starlight:tangled',
    'eternal_starlight:tangled_skull',
    'eternal_starlight:the_gatekeeper',
    'eternal_starlight:thirst_walker',
    'eternal_starlight:tiny_creteor',
    'eternal_starlight:twilight_gaze',
    'eternal_starlight:zombified_ratlin',

    // golemoverhaul
    'golemoverhaul:barrel_golem',
    'golemoverhaul:candle_golem',
    'golemoverhaul:coal_golem',
    'golemoverhaul:hay_golem',
    'golemoverhaul:honey_golem',
    'golemoverhaul:kelp_golem',
    'golemoverhaul:netherite_golem',
    'golemoverhaul:slime_golem',
    'golemoverhaul:terracotta_golem',

    // iceandfire
    'iceandfire:amphithere',
    'iceandfire:cockatrice',
    'iceandfire:cyclops',
    'iceandfire:death_worm',
    'iceandfire:dread_beast',
    'iceandfire:dread_ghoul',
    'iceandfire:dread_scuttler',
    'iceandfire:dread_spawner',
    'iceandfire:dread_thrall',
    'iceandfire:fire_dragon',
    'iceandfire:ghost',
    'iceandfire:gorgon',
    'iceandfire:hippocampus',
    'iceandfire:hippogryph',
    'iceandfire:hydra',
    'iceandfire:ice_dragon',
    'iceandfire:lich',
    'iceandfire:lightning_dragon',
    'iceandfire:pixie',
    'iceandfire:sea_serpent',
    'iceandfire:siren',
    'iceandfire:stymphalian_bird',
    'iceandfire:troll',

    // illagerinvasion
    'illagerinvasion:alchemist',
    'illagerinvasion:archivist',
    'illagerinvasion:basher',
    'illagerinvasion:firecaller',
    'illagerinvasion:illusioner',
    'illagerinvasion:inquisitor',
    'illagerinvasion:invoker',
    'illagerinvasion:marauder',
    'illagerinvasion:necromancer',
    'illagerinvasion:provoker',
    'illagerinvasion:sorcerer',
    'illagerinvasion:surrendered',

    // irons_spellbooks
    'irons_spellbooks:apothecarist',
    'irons_spellbooks:archevoker',
    'irons_spellbooks:cryomancer',
    'irons_spellbooks:dead_king_corpse',
    'irons_spellbooks:ice_spider',
    'irons_spellbooks:keeper',
    'irons_spellbooks:necromancer',
    'irons_spellbooks:priest',
    'irons_spellbooks:pyromancer',

    // mowziesmobs
    'mowziesmobs:bluff',
    'mowziesmobs:elokosa',
    'mowziesmobs:elokosa_howler',
    'mowziesmobs:foliaath',
    'mowziesmobs:frostmaw',
    'mowziesmobs:grottol',
    'mowziesmobs:lantern',
    'mowziesmobs:naga',
    'mowziesmobs:sculptor',
    'mowziesmobs:umvuthana_crane',
    'mowziesmobs:umvuthana_raptor',
    'mowziesmobs:umvuthi',
    'mowziesmobs:wroughtnaut',

    // mutantmonsters
    'mutantmonsters:mutant_creeper',
    'mutantmonsters:mutant_enderman',
    'mutantmonsters:mutant_skeleton',
    'mutantmonsters:mutant_snow_golem',
    'mutantmonsters:mutant_zombie',
    'mutantmonsters:spider_pig',

    // mythsandlegends
    'mythsandlegends:abaddon',
    'mythsandlegends:alp',
    'mythsandlegends:amarok',
    'mythsandlegends:black_charro',
    'mythsandlegends:condemned',
    'mythsandlegends:gargoyle',
    'mythsandlegends:imp',
    'mythsandlegends:karakondjul',
    'mythsandlegends:lampad',
    'mythsandlegends:possessed_armor_inquisitor',
    'mythsandlegends:scorched_sentinel',

    // royalvariations
    'royalvariations:royal_creeper',
    'royalvariations:royal_enderman',
    'royalvariations:royal_skeleton',
    'royalvariations:royal_zombie',
  ]);
});
