ServerEvents.recipes((event) => {
  const id_prefix = 'mt:hazennstuff/spirit_infusion/';

  const recipes = [
    // Seraph Armor (Sacred)
    {
      result: { id: 'hazennstuff:seraph_helmet', count: 1 },
      input: { item: 'irons_spellbooks:priest_helmet', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:divinite_shard' },
        { item: 'mythsandlegends:possessed_armor_fragment', count: 4 },
      ],
      spirits: [{ type: 'malum:sacred', count: 64 }],
      id: `${id_prefix}seraph_helmet`,
    },
    {
      result: { id: 'hazennstuff:seraph_chestplate', count: 1 },
      input: { item: 'irons_spellbooks:priest_chestplate', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:divinite_shard' },
        { item: 'mythsandlegends:possessed_armor_fragment', count: 4 },
      ],
      spirits: [{ type: 'malum:sacred', count: 64 }],
      id: `${id_prefix}seraph_chestplate`,
    },
    {
      result: { id: 'hazennstuff:seraph_leggings', count: 1 },
      input: { item: 'irons_spellbooks:priest_leggings', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:divinite_shard' },
        { item: 'mythsandlegends:possessed_armor_fragment', count: 4 },
      ],
      spirits: [{ type: 'malum:sacred', count: 64 }],
      id: `${id_prefix}seraph_leggings`,
    },
    {
      result: { id: 'hazennstuff:seraph_boots', count: 1 },
      input: { item: 'irons_spellbooks:priest_boots', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:divinite_shard' },
        { item: 'mythsandlegends:possessed_armor_fragment', count: 4 },
      ],
      spirits: [{ type: 'malum:sacred', count: 64 }],
      id: `${id_prefix}seraph_boots`,
    },
    // Cryogenic Ruler Armor (Aqueous)
    {
      result: { id: 'hazennstuff:cryogenic_ruler_helmet', count: 1 },
      input: { item: 'irons_spellbooks:cryomancer_helmet', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:ice_shard' },
        { item: 'mythsandlegends:possessed_armor_fragment', count: 4 },
      ],
      spirits: [{ type: 'malum:aqueous', count: 64 }],
      id: `${id_prefix}cryogenic_ruler_helmet`,
    },
    {
      result: { id: 'hazennstuff:cryogenic_ruler_chestplate', count: 1 },
      input: { item: 'irons_spellbooks:cryomancer_chestplate', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:ice_shard' },
        { item: 'mythsandlegends:possessed_armor_fragment', count: 4 },
      ],
      spirits: [{ type: 'malum:aqueous', count: 64 }],
      id: `${id_prefix}cryogenic_ruler_chestplate`,
    },
    {
      result: { id: 'hazennstuff:cryogenic_ruler_leggings', count: 1 },
      input: { item: 'irons_spellbooks:cryomancer_leggings', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:ice_shard' },
        { item: 'mythsandlegends:possessed_armor_fragment', count: 4 },
      ],
      spirits: [{ type: 'malum:aqueous', count: 64 }],
      id: `${id_prefix}cryogenic_ruler_leggings`,
    },
    {
      result: { id: 'hazennstuff:cryogenic_ruler_boots', count: 1 },
      input: { item: 'irons_spellbooks:cryomancer_boots', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:ice_shard' },
        { item: 'mythsandlegends:possessed_armor_fragment', count: 4 },
      ],
      spirits: [{ type: 'malum:aqueous', count: 64 }],
      id: `${id_prefix}cryogenic_ruler_boots`,
    },
    // Blazeborne Armor (Infernal)
    {
      result: { id: 'hazennstuff:blazeborne_helmet', count: 1 },
      input: { item: 'irons_spellbooks:pyromancer_helmet', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:volcanite_shard' },
        { item: 'mythsandlegends:possessed_armor_fragment', count: 4 },
      ],
      spirits: [{ type: 'malum:infernal', count: 64 }],
      id: `${id_prefix}blazeborne_helmet`,
    },
    {
      result: { id: 'hazennstuff:blazeborne_chestplate', count: 1 },
      input: { item: 'irons_spellbooks:pyromancer_chestplate', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:volcanite_shard' },
        { item: 'mythsandlegends:possessed_armor_fragment', count: 4 },
      ],
      spirits: [{ type: 'malum:infernal', count: 64 }],
      id: `${id_prefix}blazeborne_chestplate`,
    },
    {
      result: { id: 'hazennstuff:blazeborne_leggings', count: 1 },
      input: { item: 'irons_spellbooks:pyromancer_leggings', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:volcanite_shard' },
        { item: 'mythsandlegends:possessed_armor_fragment', count: 4 },
      ],
      spirits: [{ type: 'malum:infernal', count: 64 }],
      id: `${id_prefix}blazeborne_leggings`,
    },
    {
      result: { id: 'hazennstuff:blazeborne_boots', count: 1 },
      input: { item: 'irons_spellbooks:pyromancer_boots', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:volcanite_shard' },
        { item: 'mythsandlegends:possessed_armor_fragment', count: 4 },
      ],
      spirits: [{ type: 'malum:infernal', count: 64 }],
      id: `${id_prefix}blazeborne_boots`,
    },
    // Ender Dragon Armor (Eldritch)
    {
      result: { id: 'hazennstuff:ender_dragon_helmet', count: 1 },
      input: { item: 'irons_spellbooks:shadowwalker_helmet', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:voidstone_shard' },
        { item: 'mythsandlegends:possessed_armor_fragment', count: 4 },
      ],
      spirits: [{ type: 'malum:eldritch', count: 64 }],
      id: `${id_prefix}ender_dragon_helmet`,
    },
    {
      result: { id: 'hazennstuff:ender_dragon_chestplate', count: 1 },
      input: { item: 'irons_spellbooks:shadowwalker_chestplate', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:voidstone_shard' },
        { item: 'mythsandlegends:possessed_armor_fragment', count: 4 },
      ],
      spirits: [{ type: 'malum:eldritch', count: 64 }],
      id: `${id_prefix}ender_dragon_chestplate`,
    },
    {
      result: { id: 'hazennstuff:ender_dragon_leggings', count: 1 },
      input: { item: 'irons_spellbooks:shadowwalker_leggings', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:voidstone_shard' },
        { item: 'mythsandlegends:possessed_armor_fragment', count: 4 },
      ],
      spirits: [{ type: 'malum:eldritch', count: 64 }],
      id: `${id_prefix}ender_dragon_leggings`,
    },
    {
      result: { id: 'hazennstuff:ender_dragon_boots', count: 1 },
      input: { item: 'irons_spellbooks:shadowwalker_boots', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:voidstone_shard' },
        { item: 'mythsandlegends:possessed_armor_fragment', count: 4 },
      ],
      spirits: [{ type: 'malum:eldritch', count: 64 }],
      id: `${id_prefix}ender_dragon_boots`,
    },
    // Creaking Armor (Earthen)
    {
      result: { id: 'hazennstuff:creaking_helmet', count: 1 },
      input: { item: 'irons_spellbooks:plagued_helmet', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:floralite_shard' },
        { item: 'mythsandlegends:possessed_armor_fragment', count: 4 },
      ],
      spirits: [{ type: 'malum:earthen', count: 64 }],
      id: `${id_prefix}creaking_helmet`,
    },
    {
      result: { id: 'hazennstuff:creaking_chestplate', count: 1 },
      input: { item: 'irons_spellbooks:plagued_chestplate', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:floralite_shard' },
        { item: 'mythsandlegends:possessed_armor_fragment', count: 4 },
      ],
      spirits: [{ type: 'malum:earthen', count: 64 }],
      id: `${id_prefix}creaking_chestplate`,
    },
    {
      result: { id: 'hazennstuff:creaking_leggings', count: 1 },
      input: { item: 'irons_spellbooks:plagued_leggings', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:floralite_shard' },
        { item: 'mythsandlegends:possessed_armor_fragment', count: 4 },
      ],
      spirits: [{ type: 'malum:earthen', count: 64 }],
      id: `${id_prefix}creaking_leggings`,
    },
    {
      result: { id: 'hazennstuff:creaking_boots', count: 1 },
      input: { item: 'irons_spellbooks:plagued_boots', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:floralite_shard' },
        { item: 'mythsandlegends:possessed_armor_fragment', count: 4 },
      ],
      spirits: [{ type: 'malum:earthen', count: 64 }],
      id: `${id_prefix}creaking_boots`,
    },
    // Charged Scourge Armor (Aerial)
    {
      result: { id: 'hazennstuff:charged_scourge_helmet', count: 1 },
      input: { item: 'irons_spellbooks:electromancer_helmet', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:voltite_shard' },
        { item: 'mythsandlegends:possessed_armor_fragment', count: 4 },
      ],
      spirits: [{ type: 'malum:aerial', count: 64 }],
      id: `${id_prefix}charged_scourge_helmet`,
    },
    {
      result: { id: 'hazennstuff:charged_scourge_chestplate', count: 1 },
      input: { item: 'irons_spellbooks:electromancer_chestplate', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:voltite_shard' },
        { item: 'mythsandlegends:possessed_armor_fragment', count: 4 },
      ],
      spirits: [{ type: 'malum:aerial', count: 64 }],
      id: `${id_prefix}charged_scourge_chestplate`,
    },
    {
      result: { id: 'hazennstuff:charged_scourge_leggings', count: 1 },
      input: { item: 'irons_spellbooks:electromancer_leggings', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:voltite_shard' },
        { item: 'mythsandlegends:possessed_armor_fragment', count: 4 },
      ],
      spirits: [{ type: 'malum:aerial', count: 64 }],
      id: `${id_prefix}charged_scourge_leggings`,
    },
    {
      result: { id: 'hazennstuff:charged_scourge_boots', count: 1 },
      input: { item: 'irons_spellbooks:electromancer_boots', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:voltite_shard' },
        { item: 'mythsandlegends:possessed_armor_fragment', count: 4 },
      ],
      spirits: [{ type: 'malum:aerial', count: 64 }],
      id: `${id_prefix}charged_scourge_boots`,
    },
    // Flesh Mass Armor (Wicked)
    {
      result: { id: 'hazennstuff:flesh_mass_helmet', count: 1 },
      input: { item: 'irons_spellbooks:cultist_helmet', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:hemalite_shard' },
        { item: 'mythsandlegends:possessed_armor_fragment', count: 4 },
      ],
      spirits: [{ type: 'malum:wicked', count: 64 }],
      id: `${id_prefix}flesh_mass_helmet`,
    },
    {
      result: { id: 'hazennstuff:flesh_mass_chestplate', count: 1 },
      input: { item: 'irons_spellbooks:cultist_chestplate', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:hemalite_shard' },
        { item: 'mythsandlegends:possessed_armor_fragment', count: 4 },
      ],
      spirits: [{ type: 'malum:wicked', count: 64 }],
      id: `${id_prefix}flesh_mass_chestplate`,
    },
    {
      result: { id: 'hazennstuff:flesh_mass_leggings', count: 1 },
      input: { item: 'irons_spellbooks:cultist_leggings', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:hemalite_shard' },
        { item: 'mythsandlegends:possessed_armor_fragment', count: 4 },
      ],
      spirits: [{ type: 'malum:wicked', count: 64 }],
      id: `${id_prefix}flesh_mass_leggings`,
    },
    {
      result: { id: 'hazennstuff:flesh_mass_boots', count: 1 },
      input: { item: 'irons_spellbooks:cultist_boots', count: 1 },
      extraInputs: [
        { item: 'hazennstuff:deus_essence', count: 4 },
        { item: 'hazennstuff:zenalite_ingot', count: 4 },
        { item: 'irons_spellbooks:mithril_weave', count: 4 },
        { item: 'crystal_chronicles:hemalite_shard' },
        { item: 'mythsandlegends:possessed_armor_fragment', count: 4 },
      ],
      spirits: [{ type: 'malum:wicked', count: 64 }],
      id: `${id_prefix}flesh_mass_boots`,
    },
  ];

  recipes.forEach((recipe) => {
    recipe.type = 'malum:spirit_infusion';
    event.custom(recipe).id(recipe.id);
  });
});
